version: '3.8'

services:
  backend:
    build: .
    container_name: hospital_backend
    ports:
      - "7200:7200"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "node", "index.js" ]
